spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nucleic_acid?serverTimezone=UTC
    username: root
    password: xct19991101
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.honzh.demo-module.pojo
  type-aliases-package: com.higher.scancodescollect.pojo